version: '3.2'
services:
  web:
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
    - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php
  php:
    image: php:7.0-fpm
    volumes:
    - ./app:/var/www/html
