version: '3.2'
services:
  php_fpm:
    build:
      context: php-fpm
    volumes:
    - sock:/sock
  nginx_backend:
    build:
      context: nginx-backend
    ports:
    - "80:80"
    volumes:
    - sock:/sock
volumes:
  sock:
    driver: local